[package]
name = "grrs"
version = "0.1.3"
edition = "2024"

[dependencies]
clap = {version="4.0", features=["derive"]}
anyhow = "1.0"
strum = {version = "0.27", features = ["derive"]}
strum_macros = "0.27"
tabled = "0.20.0"